lint fixes

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -1,4 +1,10 @@
 #!/bin/sh
+#
+## This is the git pre-hook script, executed before pushing on remote.
+## The git pre-push hook uses ansible-lint to validate ansible playbooks YAML
+## files on commits.
+## - Make sure ansible-lint is installed
+#
 
 set -e
 
@@ -11,103 +17,99 @@ set -e
 # url="$2"
 z40=0000000000000000000000000000000000000000
 
-# Check if ansible is usable
-ansible-lint --version >/dev/null || {
-    cat >&2 <<- EOF
-
-    Please make sure ansible-lint is installed and usable.
-
-    The git pre-push hook uses ansible-lint to validate ansible playbooks YAML
-    files on commits.
-
-    EOF
+# Check if ansible-lint is usable
+if ! ansible-lint --version >/dev/null 2>&1; then
+    sed -En 's/^## //p' $0
     exit 1
-}
+fi
+
+# Initialise variables
+git_top_level=$(git rev-parse --show-toplevel)
 
 # Create the logs directory if not exists. It is ignored by git anyway
 test -d logs || mkdir logs
 
 while read -r local_ref local_sha _ _     # remote_ref and remote_sha are not used
 do
-    if [ "$local_sha" = $z40 ]
-    then
-        # Handle delete
+    # Handle delete
+    if [ "$local_sha" = $z40 ]; then
         # Do not run ansible-lint on the branch to be deleted
         :
         # Continue processing the next branch if any
-    else
-        echo "Let's check files with ansible-lint"
+        continue
+    fi
 
-        # Create a temporary file to list ansible files to check
-        tmp_checklist=$(mktemp)
+    echo "Let's check files with ansible-lint"
 
-        # Write the list of the main ansible files and directories
-        find \
-            roles/* \
-            -maxdepth 0 -print0 \
-            > "$tmp_checklist"
+    # Create a temporary file to list ansible files to check
+    tmp_checklist=$(mktemp)
 
-        # Create a temporary directory
-        tmp_dir="$(mktemp -d)"
+    # Write the list of the main ansible files and directories
+    find \
+        roles/* \
+        -maxdepth 0 -print0 \
+        > "$tmp_checklist"
 
-        # Set the log file
-        log_file="$(git rev-parse --show-toplevel)/logs/ansible-lint-pre-push.log"
+    # Create a temporary directory
+    tmp_dir="$(mktemp -d)"
 
-        # Export the branch to the temporary directory
-        echo "Exporting $local_ref to $tmp_dir"
-        git archive "$local_sha" | tar -x -C "$tmp_dir" || exit $?
+    # Set the log file
+    log_file="${git_top_level}/logs/ansible-lint-pre-push.log"
 
-        # Use a subshell to get to the temporary directory, run ansible-lint
-        # with a different error handling, and remember the exit status of the
-        # xargs call if any error
-        lint_result=0
-        (
-            cd "$tmp_dir"
+    # Export the branch to the temporary directory
+    echo "Exporting $local_ref to $tmp_dir"
+    git archive "$local_sha" | tar -x -C "$tmp_dir" || exit $?
 
-            # Do not exit on error until the end of the subshell
-            set +e
+    # Use a subshell to get to the temporary directory, run ansible-lint
+    # with a different error handling, and remember the exit status of the
+    # xargs call if any error
+    lint_result=0
+    (
+        cd "$tmp_dir"
 
-            echo "Running ansible-lint on all playbooks"
-            echo "Full log is being written to $log_file"
-            #  -x 106,207,208
-            # shellcheck disable=SC2016
-            xargs -0 -I {} \
-                sh -c 'PYTHONUNBUFFERED=1 ansible-lint "$1" 2>&1' -- "{}" \
-                < "$tmp_checklist" \
-                > "$log_file"
+        # Do not exit on error until the end of the subshell
+        set +e
+
+        echo "Running ansible-lint on all playbooks"
+        echo "Full log is being written to $log_file"
+        #  -x 106,207,208
+        # shellcheck disable=SC2016
+        xargs -0 -I {} \
+            sh -c 'PYTHONUNBUFFERED=1 ansible-lint "$1" 2>&1' -- "{}" \
+            < "$tmp_checklist" \
+            > "$log_file"
 
         # Back to: set -e
-        ) || lint_result=$?
+    ) || lint_result=$?
 
-        # Remove the temporary directory
-        rm -rf "$tmp_dir"
+    # Remove the temporary directory
+    rm -rf "$tmp_dir"
 
-        # Remove the temporary checklist file
-        rm -f "$tmp_checklist"
+    # Remove the temporary checklist file
+    rm -f "$tmp_checklist"
 
-        case "$lint_result" in
-            "0")
-                if grep --color=auto -h -e 'WARNING:' "$log_file" >&2
-                then
-                    echo "Please address the ansible-lint warnings"
-                    exit 1
-                fi
-                echo "Looks good for ansible-lint"
-                # Continue processing the next branch if any
-                ;;
-            "123")
-                grep --color=auto -h -A 11 -e 'Syntax Error' "$log_file" >&2 || true
-                grep --color=auto -h -e '\[E...]' "$log_file" >&2 || true
-                grep --color=auto -h -e 'WARNING:' "$log_file" >&2 || true
-                echo "Please fix the ansible-lint errors and warnings"
-                exit $lint_result
-                ;;
-            *)
-                echo >&2 "Sorry, something wrong happened"
-                exit $lint_result
-                ;;
-        esac
-    fi
+    case "$lint_result" in
+        "0")
+            if grep --color=auto -h -e 'WARNING:' "$log_file" >&2
+            then
+                echo "Please address the ansible-lint warnings"
+                exit 1
+            fi
+            echo "Looks good for ansible-lint"
+            # Continue processing the next branch if any
+            ;;
+        "123")
+            grep --color=auto -h -A 11 -e 'Syntax Error' "$log_file" >&2 || true
+            grep --color=auto -h -e '\[E...]' "$log_file" >&2 || true
+            grep --color=auto -h -e 'WARNING:' "$log_file" >&2 || true
+            echo "Please fix the ansible-lint errors and warnings"
+            exit $lint_result
+            ;;
+        *)
+            echo >&2 "Sorry, something wrong happened"
+            exit $lint_result
+            ;;
+    esac
 done
 
 exit 0
